### ISSUE TITLE
"apt-get upgrade" show 2 error

### ISSUE THREAD

**Issue by shariat1** [AndronixApp/AndronixOrigin#12]
I install kali. When i use command " apt-get upgrade " than show 2 error..

♦First error...

E: Setting in Start via TCSAFLUSH for stdin failed! - tcsetattr (13: Permission denied)

♦Second error...

Errors were encountered while processing:
 udisks2
 gvfs-daemons
 gvfs:armhf
E: Sub-process /usr/bin/dpkg returned an error code (1)

please help..
![Screenshot_20191102-145457](https://user-images.githubusercontent.com/43130959/68068643-1c5d5d00-fd81-11e9-80fd-c5af501b720f.png)
![Screenshot_20191102-145602](https://user-images.githubusercontent.com/43130959/68068648-2b440f80-fd81-11e9-92b6-d49b3249d167.png)

**Comment by Aerox912** [comment]
The first error is not important, just a warning but it won't impact anything.
The second issue, is known and fixed in the Desktop environment installation scripts. Advise is to start with any desktop environment installation after installing Kali, and then dist-upgrade
You'll need to reinstall Kali, though since apt is now in a state you can't easily recover from :)

**Comment by shariat1** [comment]
ok i reinstall again and try this method.
