### ISSUE TITLE
Issues in logout and exits and Fan recomendations

### ISSUE THREAD

**Issue by SaicharanKandukuri** [AndronixApp/AndronixOrigin#60]
Its been a while waiting

Hey andronix team 

I am a big fan of your works

Here are some fan recommendations
please include command `command=+ " --kill on exit " ` in your all modded and unmodded distros
lack of this line in you scripts causing problems like
- not exiting or logging out properly 
- Mostly proot binds are not closing even after logging out
- And eating up more ram and CPU

And please include the Installation folder lock or we can say (default installation location to your install scripts)
``` bash
# Like this
if [[ -z "$ANDRONIX_IHOME" ]]; then
folder="${HOME}/debian-fs"
else
    case ${ANDRONIX_IHOME} in
    /data/data/com.termux/*) folder=${ANDRONIX_IHOME} ;;
    *)
    echo
    echo "Location set to invalid destiantion ${ANDRONIX_IHOME}" 
    echo
    folder=${HOME}/debian-fs ;;
    esac
fi
```
And also additionally
- please add more dev and proc mount points
``` bash
command+="/dev/urandom:/dev/random"
# and
command+="/proc/self/fd:/dev/fd"
command+="/proc/self/fd/0:/dev/stdin"
command+="/proc/self/fd/1:/dev/stdout"
command+="/proc/self/fd/2:/dev/stderr"
```
###### And also most important
> Windows has released its official visual code studio for arm64 and arm devices so please update your vs code scripts. I made some tests on it it's working great in andronix distros and others too. So no more code-oss, please.

And we are waiting for your mic support too
And we are waiting for more optimizations and fixes in distros and modded os and multi-arch emulation with qemu

And we need more fixes and upgrades In custom procs stats and versions and more
These normal issues are leading not to love your scripts

😀
💜

**Comment by ultrahacx** [comment]
We are aware of the pending pull request but since we are planning to rewrite the scripts, it has been kept in pending. More mount points will be added too but not all of then as it might have compatibility issues for various users since OEMs change the access properties most of the time. 

Mic support is not under our list as of now due to multiple reasons. Its working will not be effecient, lags, and lack of bus and drivers which make it harder to provide mic support.

QEMU will never be supported from outside so its useless to wait for it or have any hopes (as of now)

**Comment by SaicharanKandukuri** [comment]
so new updates coming soon right!🤘

**Comment by SaicharanKandukuri** [comment]
Ok Closing Now
